import { Folder, SquarePen, Link as LinkIcon, Waypoints, Command, Mic, Brain } from "lucide-react";
import { FeatureSection } from "./FeatureSection";
import { EditorReplica } from "./EditorReplica";
import { VisTree } from "../landing/bento/VisTree";
import { VisWiki } from "../landing/bento/VisWiki";
import { VisGraph } from "../landing/bento/VisGraph";
import { VisPalette } from "../landing/bento/VisPalette";
import { VisRecorder } from "../landing/bento/VisRecorder";
import { VisMemory } from "../landing/bento/VisMemory";

const CODE = (t: string) => (
  <code style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: "0.92em" }}>{t}</code>
);

export function FeatureDeepDive() {
  return (
    <div className="f-deepdive">
      <div className="l-shell">
        <div className="l-section-head">
          <div className="l-section-label">
            <span className="l-section-label-bar" /> The workspace
          </div>
          <h2 className="l-section-title">From a blank file to a finished thought.</h2>
          <p className="l-section-sub">
            Every part of Noto works on the same plain Markdown files — so the editor,
            the links, and the graph are always looking at exactly what's on your disk.
          </p>
        </div>
      </div>

      <FeatureSection
        id="vault"
        icon={Folder}
        eyebrow="Local Markdown Vault"
        title={<>Your files. Your folders. <em>On disk.</em></>}
        desc={<>Noto reads and writes plain {CODE(".md")} in a folder you own. Nothing is trapped in a database or a vendor's cloud — the vault is just files you can open, move, and back up yourself.</>}
        bullets={[
          <>Real folders and files, browsable in the sidebar</>,
          <>Open the same vault in any other Markdown editor</>,
          <>Sync with iCloud, Dropbox, Git — whatever you already use</>,
        ]}
        cta={{ label: "See the vault format", href: "#download" }}
        media={<VisTree />}
        mediaTone="light"
      />

      <FeatureSection
        id="editor"
        icon={SquarePen}
        eyebrow="Native Markdown Editor"
        title={<>A real macOS editor, <em>not a web view.</em></>}
        desc={<>Built on {CODE("NSTextView")} for native speed and feel. Inline formatting, automatic list continuation, and smart tab indentation keep you writing instead of fighting syntax.</>}
        bullets={[
          <>{CODE("⌘B")} / {CODE("⌘I")} / {CODE("⌘U")} for bold, italic, underline</>,
          <>Press return in a list and the next bullet continues for you</>,
          <>Live wiki links, {CODE("#tags")}, and {CODE("- [ ]")} checklists</>,
        ]}
        cta={{ label: "Try the editor", href: "#preview" }}
        media={<EditorReplica />}
        mediaTone="light"
        reverse
      />

      <FeatureSection
        id="wiki"
        icon={LinkIcon}
        eyebrow="Wiki Links & Backlinks"
        title={<>Two square brackets. <em>The rest is automatic.</em></>}
        desc={<>Type {CODE("[[Chloroplast]]")} and the link is live. The destination note knows it's been linked, so backlinks are always generated by resolving every note — never authored by hand.</>}
        bullets={[
          <>Outgoing links resolve to notes anywhere in the vault</>,
          <>Backlinks appear automatically on the linked note</>,
          <>Rename-safe: links point at titles, not fragile paths</>,
        ]}
        cta={{ label: "How backlinks work", href: "#graph" }}
        media={<VisWiki />}
        mediaTone="light"
      />

      <FeatureSection
        id="graph"
        icon={Waypoints}
        eyebrow="Knowledge Web"
        title={<>Watch your ideas <em>connect themselves.</em></>}
        desc={<>Every wiki link becomes an edge; every note becomes a node. The Knowledge Web is generated from your vault, never drawn by hand — and you can filter it to focus.</>}
        bullets={[
          <>Filter to all notes, the local neighborhood, or lecture-only</>,
          <>Spot orphan notes that nothing links to yet</>,
          <>Click a node to jump straight into that note</>,
        ]}
        cta={{ label: "Open the Knowledge Web", href: "#preview" }}
        media={<div className="f-graph-host"><div className="lr-graph"><VisGraph /></div></div>}
        mediaTone="light"
        reverse
      />

      <FeatureSection
        id="palette"
        icon={Command}
        eyebrow="Command Menu"
        title={<>Everything is <em>a keystroke away.</em></>}
        desc={<>Press {CODE("⌘K")} to open the command palette and drive the entire workspace from the keyboard — jump between notes, open the graph, toggle the recorder, or insert a backlink.</>}
        bullets={[
          <>Fuzzy-jump to any note by title</>,
          <>Run actions: new note, open graph, toggle recorder</>,
          <>Never leave the keyboard to find anything</>,
        ]}
        cta={{ label: "See every shortcut", href: "#shortcuts" }}
        media={<VisPalette />}
        mediaTone="light"
      />

      {/* Lecture AI band */}
      <div className="f-lecture-band">
        <div className="l-shell">
          <div className="l-section-head">
            <div className="l-section-label">
              <span className="l-section-label-bar" /> Lecture AI
            </div>
            <h2 className="l-section-title">An assistant that listens — only when you ask.</h2>
            <p className="l-section-sub">
              Press record before a lecture or meeting. Noto follows along, drafts
              structured notes into your active file, and quietly remembers the concepts
              it heard. The moment you stop, it stops.
            </p>
          </div>
        </div>

        <FeatureSection
          id="lecture-ai"
          icon={Mic}
          eyebrow="Lecture AI Recorder"
          title={<>Press record. <em>Get structured notes.</em></>}
          desc={<>Lecture AI transcribes in real time and drafts headings, bullets, and links into the note you're already working in — so you can keep your eyes up and your hands free.</>}
          bullets={[
            <>Toggle from anywhere with {CODE("⌃⌘M")}</>,
            <>Live waveform and timer show it's listening</>,
            <>Structured notes land in your active file, not a silo</>,
          ]}
          cta={{ label: "Watch it listen", href: "#preview" }}
          media={<VisRecorder />}
          mediaTone="light"
          reverse
        />

        <FeatureSection
          id="memory"
          icon={Brain}
          eyebrow="AI Memory"
          title={<>A quiet record of <em>what you just heard.</em></>}
          desc={<>After a recording, the concepts and linked notes Lecture AI picked up are surfaced in the right-hand context panel — ready to fold into your own notes when you are.</>}
          bullets={[
            <>Key concepts extracted from the transcript</>,
            <>Suggested links to notes already in your vault</>,
            <>Nothing is written to your file without you</>,
          ]}
          cta={{ label: "See the context panel", href: "#preview" }}
          media={<VisMemory />}
          mediaTone="light"
        />
      </div>
    </div>
  );
}
