try PackageSmokeChecks.run()
try MockVaultChecks.run()
try ModelAPIChecks.run()
try MarkdownParserChecks.run()
try MetadataCacheBuilderChecks.run()
try GraphBuilderChecks.run()
print("NotoCoreChecks passed")
